#!/bin/bash
# command, arguments to command, -> command_hash.log
HASH=$(echo $@ | md5sum | cut -d' ' -f1)
mkdir -p logs
echo $@ > logs/$(basename $1)_$HASH.log
$@ | tee -a logs/$(basename $1)_$HASH.log
